
import __ASTRO_IMAGE_IMPORT_NUMdh from "./2022.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-post%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_yukc9 from "./2023.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-post%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_j3Rb1 from "./2024.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2024-post%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZzDw3P from "./discourse.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FDeploy-Discourse%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_2vmXtI from "./image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flu-tools-2024%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1G1FpC from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fissue-7%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_2nyLTw from "public/other/xuzh-com.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-a.md";
import __ASTRO_IMAGE_IMPORT_Z2agGm6 from "public/other/lcc-cc.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-b.md";
import __ASTRO_IMAGE_IMPORT_OABpD from "./prototype.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffeishu_bookkeeping_bot%2Findex.md";
import __ASTRO_IMAGE_IMPORT_hBhX7 from "./prototype.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffeishu_bookkeeping_bot%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1SHxRf from "./prototype.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffeishu_bookkeeping_bot%2Ffeishu_bot.mdx";
export default new Map([["./2022.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-post%2Findex.mdx", __ASTRO_IMAGE_IMPORT_NUMdh], ["./2023.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-post%2Findex.mdx", __ASTRO_IMAGE_IMPORT_yukc9], ["./2024.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2024-post%2Findex.mdx", __ASTRO_IMAGE_IMPORT_j3Rb1], ["./discourse.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FDeploy-Discourse%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZzDw3P], ["./image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flu-tools-2024%2Findex.mdx", __ASTRO_IMAGE_IMPORT_2vmXtI], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fissue-7%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1G1FpC], ["public/other/xuzh-com.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-a.md", __ASTRO_IMAGE_IMPORT_2nyLTw], ["public/other/lcc-cc.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-b.md", __ASTRO_IMAGE_IMPORT_Z2agGm6], ["./prototype.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffeishu_bookkeeping_bot%2Findex.md", __ASTRO_IMAGE_IMPORT_OABpD], ["./prototype.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffeishu_bookkeeping_bot%2Findex.mdx", __ASTRO_IMAGE_IMPORT_hBhX7], ["./prototype.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffeishu_bookkeeping_bot%2Ffeishu_bot.mdx", __ASTRO_IMAGE_IMPORT_Z1SHxRf]]);
		